- type: startingGear
  id: MobCargorillaGear
  equipment:
    ears: ClothingHeadsetCargo
    id: CargorillaIDCard

- type: startingGear
  id: GoblinRobeOSP
  equipment:
    outerClothing: ClothingOuterCoatRobesGoblin
    belt: ClothingBeltUtilityGoblinRandomFill

- type: startingGear
  id: GoblinKnightArmor
  equipment:
    jumpsuit: ClothingSpaceCadetJumpsuitColorBlack # temp - remove after sprite refactor
    outerClothing: ClothingOuterGoblinKnightArmor
    back: ClothingBackpackSatchelLeather
  inhand:
    - GoblinClaymore
    - WoodenBuckler